service: consumer-v3-sqs

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  extractJobsRepoBackendbr:
    handler: handler.main
    events:
      - sqs:
          arn: "arn:aws:sqs:us-east-1:507403822990:scale-producer"
          batchSize: 1

        